{
  "method": "occ",
  "description": "One-Class Classification using GODS algorithm",
  "data_path": "./data",
  "dataset": "ucf_crime",
  "input_dim": 10752,
  "n_trials": 200,
  "hyperparameters": {
    "k": {
      "type": "int",
      "min": 1,
      "max": 10,
      "description": "Number of subspaces for GODS algorithm"
    },
    "n_components": {
      "type": "int", 
      "min": 1,
      "max": 30,
      "description": "Number of PCA components for dimensionality reduction"
    }
  },
  "training": {
    "batch_size": 30,
    "test_batch_size": 1,
    "optimization_method": "L-BFGS-B",
    "pca_required": true
  },
  "evaluation": {
    "metric": "AUC",
    "direction": "maximize"
  },
  "model_params": {
    "algorithm": "GODS",
    "requires_normal_only": true,
    "supports_incremental": false
  }
}